gradescope-id = "1219999"

[roster]
"aadhya pandillapally" = "pandilla@msu.edu"
"aaryan naruka" = "narukaaa@msu.edu"
"aayush jagtap" = "jagtapaa@msu.edu"
"adam koerber" = "koerber6@msu.edu"
aditya = "jindalad@msu.edu"
"aditya aggarwal" = "aggarw75@msu.edu"
"aidan keighron" = "keighro1@msu.edu"
"ailin patimar" = "patimara@msu.edu"
"alex bitzan" = "bitzanal@msu.edu"
"alexander dallas" = "dallasa3@msu.edu"
"alexander goluska" = "goluskaa@msu.edu"
"anders nyland" = "nylanda1@msu.edu"
"anthony dono" = "donoanth@msu.edu"
"anthony gennady paremsky" = "paremsk1@msu.edu"
anubhav = "dixitanu@msu.edu"
"arafat khan" = "khanaraf@msu.edu"
"arnas kumar" = "kumararn@msu.edu"
"ashwin innuganti" = "innugant@msu.edu"
"austin archer" = "archer15@msu.edu"
"bhaavya koneru" = "konerubh@msu.edu"
"bhavya mrinal" = "mrinalbh@msu.edu"
"bingheng li" = "libinghe@msu.edu"
"bryce mayday" = "maydayb1@msu.edu"
"carlos gutierrez" = "gutie266@msu.edu"
"carolina wheeler" = "wheel340@msu.edu"
"chaitanaya pilania" = "pilaniac@msu.edu"
"chase nomer" = "nomercha@msu.edu"
"cherilyn wang" = "wangy176@msu.edu"
"chloe berry" = "berrychl@msu.edu"
"connor bechler" = "bechler4@msu.edu"
"dao chi lam" = "lamdao@msu.edu"
"david krile" = "kriledav@msu.edu"
"devendra tambat" = "tambatde@msu.edu"
"donald quillen" = "quillend@msu.edu"
"elida villegas" = "villeg39@msu.edu"
"elizabeth brust" = "brusteli@msu.edu"
"ellie xia" = "xiayili@msu.edu"
"emily evans" = "evansem9@msu.edu"
"eric wheeler" = "wheel338@msu.edu"
"erik blake-horein" = "blakehor@msu.edu"
"fangwei zhang" = "zhangf44@msu.edu"
"gary cheng" = "chenggar@msu.edu"
"geetesh girase" = "girasege@msu.edu"
"grant perlmuter" = "perlmu11@msu.edu"
"grant t gietzen" = "gietze11@msu.edu"
"gregory rivera" = "river131@msu.edu"
"hari ilango" = "ilangoha@msu.edu"
"huazhong li" = "lihuazho@msu.edu"
"imad nasser" = "nasserim@msu.edu"
"jackson honner" = "honnerja@msu.edu"
"jackson white" = "white193@msu.edu"
"jacob landess" = "landessj@msu.edu"
"jacob patton" = "patton33@msu.edu"
"jacob siemsen" = "siemsen1@msu.edu"
"jayden anderson" = "ande2575@msu.edu"
"joe vondrak" = "vondrakj@msu.edu"
"joseph doroan" = "doroanjo@msu.edu"
"joseph miller" = "mill3642@msu.edu"
"joseph robertson" = "robe1285@msu.edu"
"joseph stirling" = "stirli26@msu.edu"
"kellen blackwell" = "blackw75@msu.edu"
"ken pham" = "phammin5@msu.edu"
"krrish seth" = "sethkrri@msu.edu"
"kyle nguyen" = "nguy1219@msu.edu"
"lalo jimenez" = "jimen105@msu.edu"
"leo ramseyer" = "ramsey27@msu.edu"
"liyang xiao" = "xiaoliya@msu.edu"
"loc bui" = "builoc@msu.edu"
"logan lemon" = "lemonlog@msu.edu"
"logan pearson" = "pears272@msu.edu"
"luka jalabadze" = "jalabadz@msu.edu"
"luke briggs" = "briggsl7@msu.edu"
"madison nomer" = "nomermad@msu.edu"
"marco abat" = "abatferh@msu.edu"
"masaru mori" = "morimasa@msu.edu"
"mason hillman" = "hillma67@msu.edu"
"mason lee" = "leemason@msu.edu"
"matthew lopez" = "lopezm48@msu.edu"
"matthew white" = "white200@msu.edu"
"michael blanzy" = "blanzymi@msu.edu"
"michael dreon" = "dreonmic@msu.edu"
"michael zagotta" = "zagottam@msu.edu"
"minh gia nguyen" = "nguy1308@msu.edu"
"minh nguyen" = "nguy1056@msu.edu"
"mohini jasthi" = "jasthimo@msu.edu"
"moses barnie" = "barniemo@msu.edu"
"mujahid alnounou" = "alnouno2@msu.edu"
"nandan keshav hegde" = "hegdenan@msu.edu"
"nathan gerrow" = "gerrowna@msu.edu"
"nicolas zubieta" = "zubietan@msu.edu"
"olivia whitlock" = "whitlo34@msu.edu"
"owen irving" = "irvingow@msu.edu"
"pandiri venkata" = "pandiriv@msu.edu"
"patrick knueppel" = "knueppe3@msu.edu"
"prashant gurung" = "gurungpr@msu.edu"
"preston korytkowski" = "korytko2@msu.edu"
"quintin gutowski" = "gutows48@msu.edu"
"rahul ramamoorthy" = "ramamoo6@msu.edu"
"ram patel" = "patelram@msu.edu"
"rebant gupta" = "guptareb@msu.edu"
"robert roskowski" = "roskows5@msu.edu"
"rohan singh" = "singhro9@msu.edu"
"roshan atluri" = "atluriro@msu.edu"
"ryan krikorian" = "krikori6@msu.edu"
"sai alekhya mitta" = "mittasai@msu.edu"
"sami veliu" = "veliusam@msu.edu"
"samuel lain hedden" = "lainsamu@msu.edu"
"sania hasan" = "hasansa5@msu.edu"
sanika = "kapresan@msu.edu"
"sanjeev durge" = "durgesan@msu.edu"
"sannidhya singh" = "singhs90@msu.edu"
"sean lane" = "lanesean@msu.edu"
"shivasundhar ravi" = "ravishiv@msu.edu"
"sohaib butt" = "buttsoha@msu.edu"
"sravan kundurthi" = "kundurt1@msu.edu"
"srisruth karanam" = "karanams@msu.edu"
"toan pham" = "phamtoan@msu.edu"
"tolu fashina" = "fashinaa@msu.edu"
"varada patil" = "patilvar@msu.edu"
"vinayak challa" = "challavi@msu.edu"
"weihang hu" = "huweiha1@msu.edu"
"weiming qi" = "qiweimin@msu.edu"
"weiyi he" = "heweiyi@msu.edu"
"william kersch" = "kerschwi@msu.edu"
"william schmidtfranz" = "schmi801@msu.edu"
"xunlei qian" = "qianxunl@msu.edu"
"yash govind" = "govindya@msu.edu"
"yicheng qiao" = "qiaoyich@msu.edu"
"zachary perrico" = "perricoz@msu.edu"
"zeyuan yin" = "zeyuan@msu.edu"
